<h2>Sign up for the papi Newsletter</h2>

<div style="background:url(/images/newsletter_bg.jpg) no-repeat top center; width:740px; min-height:500px; padding:15px; margin:30px auto 0 auto;">
    <ul class="newslettersignup">
        <li>Receive information about our upcoming sales and exclusive discounts</li>
        <li>Get the latest scoop on parties and events in your area</li>
        <li>Updates on new items and styles</li>
        <li>and Much more!</li>
	</ul>
    
    <div style="filter:alpha(opacity=75); opacity: 0.75; -moz-opacity:0.75;">
	    {{block type="newsletter/subscribe" template="newsletter/subscribe.phtml"}}
	</div>
</div>
