<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
<title>Who's your papi? | PAPI INC Underwear | Men's Underwear </title> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="description" content="papi comes from the sun-bleached shores of Miami...
known through the world as America's Riviera... where the bronzed and beautiful work, play and let loose... where tropical palms sway over a seductive, multicultural world of art, fashion ans sexual energy." /> 
<meta name="keywords" content="papi underwear Cotton Stretch Mesh Platinum bikini boxer briefs thongs jock straps trunks brazilian euro sexy Men" /> 
<meta name="robots" content="INDEX,FOLLOW" /> 
<link rel="icon" href="http://papiinc.com/the-papi-store2/skin/frontend/default/papi_black/favicon.ico" type="image/x-icon" /> 
<link rel="shortcut icon" href="http://papiinc.com/the-papi-store2/skin/frontend/default/papi_black/favicon.ico" type="image/x-icon" /> 
<link rel="stylesheet" type="text/css" href="http://papiinc.com/the-papi-store2/skin/frontend/default/papi_black/css/addons.css" media="all" /> 
<link rel="stylesheet" type="text/css" href="http://papiinc.com/the-papi-store2/skin/frontend/default/papi_black/css/layout.css" media="all" /> 
<link rel="stylesheet" type="text/css" href="http://papiinc.com/the-papi-store2/skin/frontend/default/papi_black/css/theme.css" media="all" /> 
<link rel="stylesheet" type="text/css" href="http://papiinc.com/the-papi-store2/skin/frontend/default/papi_black/css/menu.css" media="all" />  
<link rel="stylesheet" href="http://papiinc.com/the-papi-store2/skin/frontend/default/default/css/colors/default.css" type="text/css" /> 
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="http://papiinc.com/the-papi-store2/skin/frontend/default/papi_black/css/ie.css" media="all" />
<![endif]--> 
<!--[if lt IE 7]>
<script type="text/javascript" src="http://papiinc.com/the-papi-store2/js/index.php?c=auto&amp;f=,lib/ds-sleight.js,varien/iehover-fix.js" ></script>
<link rel="stylesheet" type="text/css" href="http://papiinc.com/the-papi-store2/skin/frontend/default/papi_black/css/ie7minus.css" media="all" />
<![endif]--> 
<style>
/*------------------------page---------------------------*/

#page-wrap					{-moz-border-radius: 6px; clear:both; -webkit-border-radius: 6px; -khtml-border-radius: 6px; margin-bottom:10px;}

.page-content-wrap			{width:400px; height:250px; padding:0 20px 20px; position:absolute; margin:70px 0 0 520px; -moz-border-radius: 6px; -webkit-border-radius: 6px; -khtml-border-radius: 6px; }
.page-content-wrap div		{filter:alpha(opacity=50); opacity: 0.5; -moz-opacity:0.5;}
.page-content-wrap p		{text-align:justify; line-height:1.75em;}
.page-content-wrap p span	{width:115px; height:18px; margin:0 10px 0 0; float:left; background:url(images/logo-about.png) no-repeat}
/*------------------------WHO'S YOUR PAPI--------------------------------*/
a h4:hover {color:#333;}
h4 {font-size:22px; text-align:center; margin:15px; color:#980000;}
.silhouette ul { list-style-type:none; margin-top:305px; padding-left:15px; max-width:165px;}
.silhouette ul li {font-size:12px; line-height:1.3em; margin-top:10px;}
.silhouette img {margin-bottom:10px;}
.silhouette {width:192px; height:700px; display:inline; float:left; position:relative;}
.silhouette:hover {background-color:#fdeeef;}

img.fade {opacity: 1; -webkit-transition: opacity .5s linear;}
img.fade:hover {opacity: 0; filter:alpha(opacity=0);}

.shopnow { background-color:#e6d8d9; width:100px; text-align:center; padding:10px 0 10px 0; left:50px; bottom:95px; position:absolute;}
.shopnow:hover { background-color:#CCC;}
.shopnow a:link {font-size:11px; color:#980000;}
.shopnow a:visited {color:#980000;}
.shopnow a:active {color:#980000;}
.shopnow a:hover { color:#000;}
</style>

<?php include('includes/site-elements/list-of-scripts.php'); ?>
</head> 
 
<body id="bd" class=" cms-index-index cms-home fs3"> 
 
<div id="ja-wrapper"> 
 
<!-- BEGIN: HEADER --> 
        <div id="ja-headerwrap"> 
            <div id="ja-header" class="clearfix"> 
                  
                <div id="bull_account"> 
                    <a href="/the-papi-store2/checkout/cart/">MY CART</a> 
                    <a href="https://papiinc.com/the-papi-store2/customer/account/">MY ACCOUNT</a> 
                    <a href="https://papiinc.com/the-papi-store2/customer/account/login/">LOG IN</a> 
                </div> 

                <h1 id="logo"><a href="http://papiinc.com/the-papi-store2/">PAPI INC | Men's Underwear</a></h1> 
<?php include('includes/site-elements/search.php'); ?>          

<?php include('includes/site-elements/mainnav.php'); ?>
            </div> 
        </div> 
<!-- END: HEADER --> 
     
<!-- BEGIN: MAIN CONTAINER --> 
<!-- BEGIN: CONTENT --> 
<!-- primary content --> 
							<h2 id="title">Who's your papi?</h2>
                            <div style="margin: 0 auto; width:800px; overflow:hidden;">
                            	
                            	<div id="campaign-feature-wrap">
                                    <div id="page-wrap" class="campaign">
                                        <div class="silhouette" id="eurotrunk">
                                            <a href="/the-papi-store2/all-underwear/euro-trunk.html?v=who"><h4>Euro Trunk</h4></a>
                                            <div style="position: relative;">
                                                <img src="images/who/who-euro-ro.jpg" width="192" height="265" style="position: absolute; left:0;" />
                                                <a href="/the-papi-store2/all-underwear/euro-trunk.html?v=who"><img src="/images/who/who-euro.jpg" width="192" height="265" class="fade" style="position: absolute;" /></a>
                                            </div>
                                            <ul>
                                                <li>For guys who like the support of a brief with the comfort of a trunk</li>
                                                <li>Leg slit opening shows off more skin and prevents sliding under clothes</li>
                                                <li>Sporty Look</li>
                                                <li>Contour pouch provides support</li>
                                            </ul>
                                            <div class="shopnow">
                                                <a href="/the-papi-store2/all-underwear/euro-trunk.html?v=who">shop for<br>euro trunks</a>
                                            </div>
                                        </div>
                                        
                                        <div class="silhouette" id="hipster">
                                            <a href="/the-papi-store2/all-underwear/hipster.html?v=who"><h4>Hipster</h4></a>
                                            <div style="position: relative;">
                                                <img src="images/who/who-hipster-ro.jpg" width="192" height="265" style="position: absolute; left:0;" />
                                                <a href="/the-papi-store2/all-underwear/hipster.html?v=who"><img src="/images/who/who-hipster.jpg" width="192" height="265" class="fade" style="position: absolute;" /></a>
                                            </div>
                                            <ul>
                                                <li>Waistband sits on the hip and is not visible above the waistline</li>
                                                <li>Less coverage on the leg makes it ideal for sports and running</li>
                                                <li>Contour pouch provides support and lift</li>
                                                <li>Hip and cool. Popular with surfers and skaters</li>
                                            </ul>
                                            <div class="shopnow">
                                                <a href="/the-papi-store2/all-underwear/hipster.html?v=who">shop for<br> hipsters</a>
                                            </div>
                                        </div>
                                        
                                        <div class="silhouette" id="brazilian">
                                            <a href="/the-papi-store2/all-underwear/brazilian-trunk.html?v=who"><h4>Brazilian Trunk</h4></a>
                                            <div style="position: relative;">
                                            	<img src="images/who/who-brazilian-ro.jpg" width="192" height="265" style="position:absolute; left:0;" />
                                                <a href="/the-papi-store2/all-underwear/brazilian-trunk.html?v=who"><img src="/images/who/who-brazilian.jpg" width="192" height="265" class="fade" style="position:absolute;" /></a>
                                            </div>
                                            <ul>
                                                <li>Shorter version of the classic trunk design</li>
                                                <li>Super comfortable</li>
                                                <li>Slimming abilities help hide a little extra weight</li>
                                                <li>Brazilians are sexy</li>
                                            </ul>
                                            <div class="shopnow">
                                                <a href="/the-papi-store2/all-underwear/brazilian-trunk.html?v=who">shop for<br>brazilian trunks</a>
                                            </div>
                                        </div>
                                        
                                        <div class="silhouette" id="lrb">
                                            <a href="/the-papi-store2/all-underwear/low-rise-brief.html?v=who"><h4>Low Rise Brief</h4></a>
                                            <div style="position: relative;">
                                                <img src="images/who/who-brief-ro.jpg" width="192" height="265" style="position: absolute; left:0;" />
                                                <a href="/the-papi-store2/all-underwear/low-rise-brief.html?v=who"><img src="/images/who/who-brief.jpg" width="192" height="265" class="fade" style="position: absolute;" /></a>
                                            </div>
                                            <ul>
                                                <li>Great for showing off abs</li>
                                                <li>Sick with low slung jeans</li>
                                                <li>Briefs provide best support</li>
                                                <li>Briefs don't ride up</li>
                                            </ul>
                                            <div class="shopnow">
                                                <a href="/the-papi-store2/all-underwear/low-rise-brief.html?v=who">shop for<br> low rise briefs</a>
                                            </div>
                                        </div>
                                        
                                        <div class="silhouette" id="thong">
                                            <a href="/the-papi-store2/all-underwear/thong.html?v=who"><h4>Thong</h4></a>
                                            <div style="position: relative;">
                                                <img src="images/who/who-thong.jpg" width="192" height="265" style="position: absolute; left:0;" /><a href="/the-papi-store2/all-underwear/thong.html?v=who"><img src="/images/who/who-thong.jpg" width="192" height="265" class="fade" style="position: absolute;" /></a>
                                            </div>
                                            <ul>
                                                <li>Extremely sexy!!!</li>
                                                <li>Great tan line</li>
                                                <li>No lines under clothing</li>
                                                <li>Fun to wear during vacations</li>
                                                <li>Shows self-confidence and adventurous spirit</li>	
                                            </ul>
                                            <div class="shopnow">
                                                <a href="/the-papi-store2/all-underwear/thong.html?v=who">shop for<br> thongs</a>
                                            </div>
                                        </div>
                                        
                                        <div class="silhouette" id="bbrief">
                                            <a href="/the-papi-store2/all-underwear/boxer-brief.html?v=who"><h4>Boxer Briefs</h4></a>
                                            <div style="position: relative;">
                                                <img src="images/who/who-boxer-brief-ro.jpg" width="192" height="265" style="position: absolute; left:0;" /><a href="/the-papi-store2/all-underwear/boxer-brief.html?v=who"><img src="/images/who/who-boxer-brief.jpg" width="192" height="265" class="fade" style="position: absolute;" /></a>
                                            </div>
                                            <ul>
                                                <li>Sculpts the lower torso</li>
                                                <li>Works under all types of clothing</li>
                                                <li>Slimming abilities help hide a little extra weight</li>	
                                            </ul>
                                            <div class="shopnow">
                                                <a href="/the-papi-store2/all-underwear/boxer-brief.html?v=who">shop for<br> boxer briefs</a>
                                            </div>
                                        </div>
                                        
                                        
                                        
                                        <div class="silhouette" id="jock">
                                            <a href="/the-papi-store2/all-underwear/jock-strap.html?v=who"><h4>Jockstrap</h4></a>
                                            <div style="position: relative;">
                                                <img src="images/who/who-jockstrap-ro.jpg" width="192" height="265" style="position: absolute; left:0;" /><a href="/the-papi-store2/all-underwear/jock-strap.html?v=who"><img src="/images/who/who-jockstrap.jpg" width="192" height="265" class="fade" style="position: absolute;" /></a>
                                            </div>
                                            <ul>
                                                <li>Provides great support</li>
                                                <li>Fun to wear during vacations</li>
                                                <li>Shows self-confidence and adventurous spirit</li>	
                                            </ul>
                                            <div class="shopnow">
                                                <a href="/the-papi-store2/all-underwear/jock-strap.html?v=who">shop for<br> jockstraps</a>
                                            </div>
                                        </div>
                                    
                                    </div>
                            	</div>
                            </div>	      
<!-- // primary content -->
<!-- END: CONTENT --> 
<!-- END: MAIN CONTAINER -->
<?php //include('includes/site-elements/bottom-section.php'); ?>
<?php include('includes/site-elements/footer.php'); ?> 
<?php include('includes/site-elements/googlecode.php'); ?>     
</div> 
</body> 
</html>