<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>    


<ul class="links">
        <li class="first">
            <?php if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo $this->__('Login / Register') ?></a>
            <?php else: ?>
            <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>"><?php echo $this->__('Logout') ?></a>
        <?php endif; ?>
        </li>
</ul>